import { StyleSheet } from 'react-native';

import { BrandColors } from '@/constants/theme';

export const passwordRecoveryStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 32,
    paddingBottom: 36,
  },
  closeButton: {
    alignSelf: 'flex-end',
    alignItems: 'center',
    justifyContent: 'center',
    width: 42,
    height: 42,
    marginTop: 12,
    marginRight: -8,
  },
  heading: {
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 40,
    lineHeight: 48,
    textAlign: 'center',
  },
  recoveryMessage: {
    color: 'rgba(0, 0, 0, 0.9)',
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
    textAlign: 'center',
  },
  email: {
    color: 'rgba(0, 0, 0, 0.9)',
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 3,
    textAlign: 'center',
  },
  iconCircle: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    width: 112,
    height: 112,
    marginTop: 56,
    borderRadius: 56,
    backgroundColor: BrandColors.navy,
  },
  codeExpiry: {
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 22,
    textAlign: 'center',
  },
  codeRows: {
    marginTop: 52,
    rowGap: 12,
  },
  codeRowsWithExpiry: {
    marginTop: 28,
  },
  codeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    columnGap: 16,
  },
  codeInput: {
    flex: 1,
    height: 64,
    minWidth: 0,
    borderColor: 'rgba(0, 0, 0, 0.3)',
    borderWidth: 2,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.08)',
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 30,
    textAlign: 'center',
  },
  codeInputFilled: {
    backgroundColor: '#FFFFFF',
    borderColor: BrandColors.navy,
  },
  primaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 48,
    marginTop: 26,
    borderRadius: 20,
    backgroundColor: BrandColors.green,
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  buttonText: {
    color: '#FFFFFF',
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 18,
    lineHeight: 24,
  },
  secondaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 48,
    marginTop: 17,
    borderRadius: 20,
    backgroundColor: BrandColors.navy,
  },
  resendHint: {
    color: 'rgba(0, 0, 0, 0.9)',
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 13,
    fontStyle: 'italic',
    lineHeight: 20,
    marginTop: 26,
    textAlign: 'center',
  },
  resetMessage: {
    color: 'rgba(0, 0, 0, 0.9)',
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 16,
    lineHeight: 24,
    marginTop: 9,
    textAlign: 'center',
  },
  passwordForm: {
    marginTop: 32,
  },
  inputLabel: {
    color: 'rgba(0, 0, 0, 0.9)',
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 17,
    lineHeight: 24,
    marginBottom: 8,
  },
  passwordInput: {
    height: 48,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.08)',
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 16,
    marginBottom: 17,
    paddingHorizontal: 14,
  },
  requirements: {
    marginTop: 25,
    rowGap: 2,
  },
  requirementRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
  },
  requirementText: {
    color: 'rgba(0, 0, 0, 0.9)',
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: 19,
  },
  successContent: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 33,
  },
  successHeading: {
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 47,
    lineHeight: 48,
  },
  successMessage: {
    color: 'rgba(0, 0, 0, 0.9)',
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 18,
    lineHeight: 23,
    marginTop: 13,
  },
});
