import { StyleSheet } from 'react-native';

import { BrandColors } from '@/constants/theme';

export const authSignInStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-end',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderTopWidth: 1,
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    marginTop: 60,
    paddingHorizontal: 35,
    paddingTop: 22,
    paddingBottom: 30,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  title: {
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 32,
    lineHeight: 39,
    textAlign: 'center',
  },
  subtitle: {
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 1,
    textAlign: 'center',
  },
  methodSelector: {
    flexDirection: 'row',
    height: 48,
    marginTop: 29,
    backgroundColor: BrandColors.navy,
    borderRadius: 20,
    overflow: 'hidden',
  },
  methodOption: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  methodOptionActive: {
    backgroundColor: '#FFFFFF',
    borderColor: '#0D1282',
    borderWidth: 1.5,
    borderRadius: 20,
  },
  methodText: {
    color: '#FFFFFF',
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 15,
    lineHeight: 20,
  },
  methodTextActive: {
    color: '#0D1282',
  },
  form: {
    marginTop: 40,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(3, 4, 94, 0.1)',
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 1,
    borderRadius: 20,
  },
  input: {
    flex: 1,
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 12,
    marginLeft: 12,
    paddingVertical: 0,
  },
  passwordInput: {
    marginLeft: 12,
    paddingRight: 4,
  },
  passwordVisibilityButton: {
    width: 38,
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accessKeyInput: {
    marginTop: 28,
  },
  forgotPasswordButton: {
    alignSelf: 'flex-end',
    marginTop: 8,
  },
  forgotPasswordText: {
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 11,
    lineHeight: 16,
  },
  verifyButton: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 45,
    marginTop: 24,
    backgroundColor: BrandColors.navy,
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 1,
    borderRadius: 20,
  },
  verifyButtonDisabled: {
    opacity: 0.7,
  },
  verifyButtonText: {
    color: '#FFFFFF',
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 14,
    lineHeight: 20,
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 12,
    marginVertical: 22,
  },
  dividerLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(151, 151, 151, 0.5)',
  },
  dividerText: {
    color: 'rgba(3, 4, 94, 0.6)',
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 12,
    lineHeight: 18,
  },
  scanButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 8,
    height: 45,
    backgroundColor: BrandColors.green,
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 1,
    borderRadius: 20,
  },
  scanButtonText: {
    color: '#FFFFFF',
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 14,
    lineHeight: 20,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 27,
  },
  footerText: {
    color: '#0D1282',
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 10,
    lineHeight: 16,
  },
  footerLink: {
    color: '#0D1282',
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 10,
    lineHeight: 16,
  },
});
