import { StyleSheet } from 'react-native';

import { BrandColors } from '@/constants/theme';

export const merchantRegistrationStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-end',
  },
  card: {
    minHeight: 590,
    marginTop: 60,
    paddingTop: 22,
    paddingHorizontal: 30,
    paddingBottom: 32,
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderTopWidth: 1,
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  title: {
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 22,
    lineHeight: 28,
    textAlign: 'center',
  },
  description: {
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 11,
    lineHeight: 13,
    marginTop: 7,
    paddingHorizontal: 12,
    textAlign: 'center',
  },
  progress: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 18,
    marginHorizontal: -10,
  },
  progressCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#009900',
  },
  progressCircleComplete: {
    width: 35,
    height: 35,
    borderRadius: 18,
    backgroundColor: '#009900',
  },
  progressCircleCurrent: {
    backgroundColor: '#009900',
  },
  progressText: {
    color: '#009900',
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 14,
    lineHeight: 18,
  },
  progressTextCurrent: {
    color: '#FFFFFF',
  },
  progressLine: {
    flex: 1,
    height: 3,
    backgroundColor: '#009900',
  },
  form: {
    marginTop: 28,
    rowGap: 13,
  },
  fieldLabel: {
    color: '#979797',
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 12,
    lineHeight: 20,
    marginBottom: -1,
  },
  fieldInput: {
    height: 38,
    paddingHorizontal: 10,
    paddingVertical: 0,
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 13,
    backgroundColor: 'rgba(3, 4, 94, 0.1)',
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 0.5,
    borderRadius: 5,
  },
  optionLabel: {
    color: '#979797',
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 12,
    lineHeight: 20,
  },
  businessOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    columnGap: 16,
    rowGap: 8,
    marginTop: -2,
  },
  businessOption: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 76,
  },
  businessOptionWide: {
    width: 122,
  },
  checkbox: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
    backgroundColor: 'rgba(3, 4, 94, 0.1)',
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 0.5,
  },
  checkboxChecked: {
    backgroundColor: BrandColors.green,
  },
  nextButton: {
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    backgroundColor: BrandColors.navy,
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 1,
    borderRadius: 20,
  },
  nextButtonText: {
    color: '#FFFFFF',
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 14,
    lineHeight: 20,
  },
  ownerNameRow: {
    flexDirection: 'row',
    columnGap: 5,
  },
  lastNameField: {
    flex: 0.42,
  },
  firstNameField: {
    flex: 0.5,
  },
  middleInitialField: {
    flex: 0.1,
  },
  compactFieldLabel: {
    color: '#979797',
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 12,
    lineHeight: 20,
    marginBottom: -1,
  },
  compactFieldInput: {
    height: 38,
    paddingHorizontal: 8,
    paddingVertical: 0,
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 13,
    backgroundColor: 'rgba(3, 4, 94, 0.1)',
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 0.5,
    borderRadius: 5,
  },
  permitInput: {
    height: 112,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(3, 4, 94, 0.1)',
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 0.5,
    borderRadius: 5,
  },
  termsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 26,
  },
  termsText: {
    color: '#000000',
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 12,
    lineHeight: 20,
  },
  termsLink: {
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 12,
    lineHeight: 20,
  },
  termsCheckbox: {
    width: 18,
    height: 18,
    marginRight: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(3, 4, 94, 0.1)',
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 0.5,
  },
  submitButton: {
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 32,
    backgroundColor: BrandColors.navy,
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 1,
    borderRadius: 20,
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
});
