import { StyleSheet } from 'react-native';

import { BrandColors } from '@/constants/theme';

export const authVerificationStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  safeArea: {
    flex: 1,
  },
  verificationContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 36,
    paddingTop: 18,
    paddingBottom: 32,
  },
  closeButton: {
    alignSelf: 'flex-end',
    padding: 8,
  },
  title: {
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 52,
    lineHeight: 62,
    marginTop: 22,
    textAlign: 'center',
  },
  message: {
    color: 'rgba(0, 0, 0, 0.9)',
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 16,
    lineHeight: 22,
    marginTop: 30,
    textAlign: 'center',
  },
  email: {
    color: 'rgba(0, 0, 0, 0.9)',
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 16,
    lineHeight: 22,
    marginTop: 3,
    textAlign: 'center',
  },
  emailIcon: {
    width: 115,
    height: 115,
    borderRadius: 58,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: BrandColors.navy,
    marginTop: 20,
  },
  verificationHint: {
    color: 'rgba(0, 0, 0, 0.9)',
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 16,
    fontStyle: 'italic',
    lineHeight: 22,
    marginTop: 17,
    textAlign: 'center',
  },
  codeRow: {
    width: '100%',
    flexDirection: 'row',
    columnGap: 8,
    marginTop: 28,
  },
  codeInput: {
    flex: 1,
    height: 60,
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 24,
    textAlign: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.08)',
    borderColor: 'rgba(0, 0, 0, 0.3)',
    borderWidth: 2,
    borderRadius: 10,
  },
  primaryButton: {
    width: '100%',
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: BrandColors.green,
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 1,
    borderRadius: 20,
    marginTop: 35,
  },
  secondaryButton: {
    width: '100%',
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: BrandColors.navy,
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 1,
    borderRadius: 20,
    marginTop: 17,
    paddingHorizontal: 16,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  buttonText: {
    color: '#FFFFFF',
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 20,
    lineHeight: 24,
    textAlign: 'center',
  },
  resendHint: {
    color: 'rgba(0, 0, 0, 0.9)',
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: 18,
    marginTop: 20,
    textAlign: 'center',
  },
  splashContent: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 60,
    paddingBottom: 100,
  },
  splashTitle: {
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 52,
    lineHeight: 55,
  },
  splashWelcome: {
    flexDirection: 'row',
    alignItems: 'baseline',
    flexWrap: 'wrap',
    marginTop: 14,
  },
  splashWelcomeText: {
    color: 'rgba(0, 0, 0, 0.9)',
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 20,
    lineHeight: 26,
  },
  splashRelief: {
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 20,
    lineHeight: 26,
  },
  splashChain: {
    color: BrandColors.green,
    fontFamily: 'Sarina_400Regular',
    fontSize: 20,
    lineHeight: 26,
    marginLeft: 4,
  },
});
