import { StyleSheet } from 'react-native';

import { BrandColors } from '@/constants/theme';

export const registrationStyles = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#FFFFFF' },
  safeArea: { flex: 1 },
  scrollContent: { flexGrow: 1, justifyContent: 'flex-end' },
  card: {
    minHeight: 600,
    marginTop: 56,
    paddingTop: 24,
    paddingHorizontal: 28,
    paddingBottom: 34,
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderTopWidth: 1,
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  title: {
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 22,
    lineHeight: 28,
    textAlign: 'center',
  },
  description: {
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_400Regular',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 6,
    paddingHorizontal: 10,
    textAlign: 'center',
  },
  progress: { flexDirection: 'row', alignItems: 'center', marginTop: 20 },
  progressLine: { flex: 1, height: 3, backgroundColor: BrandColors.green },
  progressCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: BrandColors.green,
    backgroundColor: '#FFFFFF',
  },
  progressCircleActive: { backgroundColor: BrandColors.green },
  progressText: { color: BrandColors.green, fontFamily: 'PlusJakartaSans_700Bold', fontSize: 13 },
  progressTextActive: { color: '#FFFFFF' },
  form: { marginTop: 24, rowGap: 12 },
  row: { flexDirection: 'row', columnGap: 8 },
  flexField: { flex: 1 },
  demographicRow: { flexDirection: 'row', alignItems: 'flex-start', columnGap: 12 },
  demographicSex: { flex: 0.4 },
  demographicCivil: { flex: 0.6 },
  passwordRow: { flexDirection: 'row', columnGap: 10 },
  nameRow: { flexDirection: 'row', alignItems: 'flex-end', columnGap: 6 },
  nameField: { flex: 0.42 },
  initialField: { flex: 0.16 },
  fieldLabelRow: { flexDirection: 'row', alignItems: 'center' },
  fieldLabel: { color: BrandColors.grey, fontFamily: 'PlusJakartaSans_500Medium', fontSize: 12, lineHeight: 18 },
  required: { color: BrandColors.navy, fontFamily: 'PlusJakartaSans_700Bold', marginLeft: 3 },
  inputWrap: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(17, 46, 88, 0.10)',
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 0.5,
    borderRadius: 5,
  },
  input: {
    flex: 1,
    minHeight: 38,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: BrandColors.navy,
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 13,
  },
  multilineInput: { minHeight: 76, textAlignVertical: 'top' },
  inputAction: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center' },
  choices: { flexDirection: 'row', flexWrap: 'wrap', columnGap: 8, rowGap: 4 },
  choice: {
    width: '47%',
    minHeight: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  choiceFull: { width: '100%' },
  choiceIndicator: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
    backgroundColor: 'rgba(17, 46, 88, 0.10)',
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 0.5,
  },
  choiceIndicatorSelected: { backgroundColor: BrandColors.green },
  choiceText: { color: BrandColors.grey, fontFamily: 'PlusJakartaSans_500Medium', fontSize: 10 },
  upload: {
    minHeight: 112,
    alignItems: 'center',
    justifyContent: 'center',
    rowGap: 6,
    backgroundColor: 'rgba(17, 46, 88, 0.10)',
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 0.5,
    borderRadius: 5,
  },
  uploadText: { color: BrandColors.grey, fontFamily: 'PlusJakartaSans_500Medium', fontSize: 12, textAlign: 'center', paddingHorizontal: 12 },
  uploadTextSelected: { color: BrandColors.navy },
  dateInput: {
    minHeight: 38,
    justifyContent: 'center',
    paddingHorizontal: 12,
    backgroundColor: 'rgba(17, 46, 88, 0.10)',
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 0.5,
    borderRadius: 5,
  },
  dateText: { color: BrandColors.navy, fontFamily: 'PlusJakartaSans_500Medium', fontSize: 13 },
  datePlaceholder: { color: BrandColors.grey, fontFamily: 'PlusJakartaSans_500Medium', fontSize: 13 },
  datePickerWrap: { marginTop: 6, borderRadius: 8, backgroundColor: BrandColors.lightGray, overflow: 'hidden' },
  dateDone: { alignSelf: 'flex-end', paddingHorizontal: 16, paddingVertical: 10 },
  dateDoneText: { color: BrandColors.navy, fontFamily: 'PlusJakartaSans_700Bold', fontSize: 13 },
  button: {
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
    backgroundColor: BrandColors.navy,
    borderColor: 'rgba(151, 151, 151, 0.5)',
    borderWidth: 0.5,
    borderRadius: 20,
  },
  buttonDisabled: { opacity: 0.65 },
  buttonText: { color: '#FFFFFF', fontFamily: 'PlusJakartaSans_500Medium', fontSize: 14 },
  terms: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 8, columnGap: 8 },
  checkbox: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: BrandColors.grey,
    backgroundColor: '#FFFFFF',
  },
  checkboxChecked: { borderColor: BrandColors.green, backgroundColor: BrandColors.green },
  termsText: { color: BrandColors.navy, fontFamily: 'PlusJakartaSans_400Regular', fontSize: 12 },
  termsLink: { color: BrandColors.navy, fontFamily: 'PlusJakartaSans_700Bold' },
  passwordCriteria: { marginTop: 4, rowGap: 2 },
  criteriaTitle: { color: BrandColors.navy, fontFamily: 'PlusJakartaSans_600SemiBold', fontSize: 10, lineHeight: 14 },
  criteriaRow: { flexDirection: 'row', alignItems: 'center', columnGap: 6 },
  criteriaText: { color: BrandColors.grey, fontFamily: 'PlusJakartaSans_400Regular', fontSize: 10, lineHeight: 14 },
  criteriaMet: { color: BrandColors.green },
});
